### ISSUE TITLE
Set XCURSOR_PATH

### ISSUE THREAD

**Issue by orowith2os** [flathub/org.electronjs.Electron2.BaseApp#42]
Electron applications that use Wayland need `XCURSOR_PATH` to be set, as Chromium ships its own `wayland-protocols`. 

Currently, many applications that *can* run on native Wayland (even if not doing so by default) set this in their permissions. It would be ideal for this BaseApp to set it by itself.

`--env=XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons`

**Comment by Erick555** [comment]
I didn't saw a BaseApp setting any permission and I doubt it would have effect on apps using it.

**Comment by orowith2os** [comment]
It can probably be set in zypak somewhere.

**Comment by bbhtt** [comment]
I opened an issue for zypak. Permissions from baseapps don't get inherited into the app, a baseapp is a regular app in the context of flatpak. Only context from runtimes get merged into the app by flatpak.

There's also no way to do this through a config file etc. in the baseapp.

It should either stay in the app, be set in zypak or be fixed in Chromium.

I think it's better to close this. Maybe it can be documented in wiki, but I don't have permission to enable that here.
